package com.ebizx.file;

import com.ebizx.file.EbizxFileUtils.*;

import java.io.File;
import java.math.BigInteger;
import java.util.ArrayList;
import org.apache.commons.io.FileUtils;
import junit.framework.TestCase;

public class EbizxFileUtilsTest extends TestCase {

	
	public void test_largestDirectory_A$File() throws Exception {
		// TODO auto-generated by JUnit Helper.
		File directory = new File("C:\\Apps\\code\\workspace\\IOMe\\WEB-INF\\classes\\com\\serus");
		File actual = EbizxFileUtils.largestDirectory(directory);
		System.out.println(actual.getName());
		//File expected = null;
		//assertEquals(expected, actual);
	}

	

}
